### ISSUE TITLE
Cool! OpenFL? 

### ISSUE THREAD

**Issue by cambiata** [nensanders/aggx#1]
Seems like a great lib!
Does it work using OpenFL?
Are you planning to convert the whole AGG lib to Haxe?

**Comment by nensanders** [comment]
Hi Jonas,
Currently its using pure flash bindings from haxe. Not openfl.
I have plans to integrate within the duell ecosystem to support more platforms, namely iOS, Android, HTML5.
It uses the flash domain memory, which is needed to be ported to the other targets.
Another plan is to integrate svg rendering with it. I already found a C# port of AGG which supports that, so it should be ok.
